version: '3.8'

services:
  client:
    image: tanimur/client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - api

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/clickup
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-at-least-32-characters-long}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - API_PREFIX=/api/v1
      - DEBUG=True
      - ENVIRONMENT=development
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8000
    volumes:
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clickup
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
